// Bedarfs-Kategorien: wonach Menschen suchen (siehe suchanfragen.md), abgebildet auf Kategorien und Leistungen.
// ohneKarte: Rubrik ist eine reine Infoseite, Kachel auf der Startseite verlinkt dorthin statt die Karte zu filtern
// match: Liste von [Kategorie, Leistung oder '*' für alle Einträge der Kategorie]
export const BEDARF = [
  { key: 'strumpf', words: 'stützstrümpfe kompressionsstrümpfe kompressionsstrumpf medizinische strümpfe socken thrombosestrümpfe venen krampfadern lymphödem flachstrick rundstrick', label: 'Stützstrümpfe & Kompressionsstrümpfe', short: 'Stützstrümpfe', match: [['sanitaetshaus', 'kompression'], ['sanitaetshaus', 'lymph']], leistung: 'kompressionsstruempfe' },
  { key: 'einlagen', words: 'einlagen schuheinlagen orthopädische schuhe fußanalyse fersensporn plattfuß diabetikerschuhe maßschuhe', label: 'Einlagen & orthopädische Schuhe', short: 'Einlagen', match: [['sanitaetshaus', 'einlagen'], ['sanitaetshaus', 'schuhtechnik']], leistung: 'einlagen-fussanalyse' },
  { key: 'rollator', words: 'rollator gehhilfe gehwagen gehstock krücken unterarmgehstützen', label: 'Rollator & Gehhilfen', short: 'Rollator', match: [['sanitaetshaus', 'rollator']], leistung: 'rollator' },
  { key: 'pflegebett', words: 'pflegebett krankenbett niedrigbett bett für zuhause matratze antidekubitus', label: 'Pflegebett & Krankenbett', short: 'Pflegebett', match: [['sanitaetshaus', 'pflegebett']], leistung: 'pflegebett' },
  { key: 'rollstuhl', words: 'rollstuhl elektrorollstuhl scooter elektromobil rollstuhl reparatur', label: 'Rollstuhl & Reparatur', short: 'Rollstuhl', match: [['sanitaetshaus', 'rollstuhl']], leistung: 'rollstuhl-werkstatt' },
  { key: 'bandagen', words: 'bandage orthese prothese kniebandage schiene orthopädietechnik beinprothese', label: 'Bandagen, Orthesen & Prothesen', short: 'Bandagen', match: [['sanitaetshaus', 'bandagen'], ['sanitaetshaus', 'orthopaedietechnik']], leistung: 'prothesen-orthesen' },
  { key: 'brust', words: 'brustprothese epithese brust-op mastektomie spezial-bh', label: 'Brustprothese nach Brust-OP', short: 'Brustprothese', match: [['sanitaetshaus', 'brustprothetik']], leistung: 'brustprothetik' },
  { key: 'inko', words: 'inkontinenz windeln stoma katheter vorlagen', label: 'Inkontinenz & Stoma', short: 'Inkontinenz', match: [['sanitaetshaus', 'stoma'], ['apotheke', 'inkontinenz']], leistung: 'stoma-inkontinenz' },
  { key: 'zuhause', words: 'pflegedienst ambulante pflege hausbesuch versorgung zu hause häusliche pflege', label: 'Versorgung zu Hause', short: 'Zu Hause', hint: 'Pflegedienste und Hausbesuche', match: [['pflege', '*'], ['sanitaetshaus', 'hausbesuch'], ['physio', 'hausbesuch']], seite: 'pflegedienst' },
  { key: 'physio', words: 'physiotherapie krankengymnastik physiotherapeut massage lymphdrainage manuelle therapie', label: 'Physiotherapie', short: 'Physiotherapie', match: [['physio', '*']], seite: 'physiotherapie' },
  { key: 'fahrt', words: 'krankenfahrt krankentransport taxi dialysefahrt chemo fahrdienst', label: 'Fahrt zur Behandlung', short: 'Krankenfahrt', hint: 'Krankenfahrten, Dialyse, Chemo', match: [['fahrt', '*']], seite: 'krankenfahrten' },
  { key: 'heim', words: 'pflegeheim altenheim seniorenheim seniorenresidenz kurzzeitpflege heimplatz stationäre pflege betreutes wohnen', label: 'Pflegeheim & Kurzzeitpflege', short: 'Pflegeheim', hint: 'Heime, Kurzzeitpflege, betreutes Wohnen', match: [['heim', '*']], seite: 'pflegeheim' },
  { key: 'pflegebox', words: 'pflegeprodukte pflegebox pflegehilfsmittel handschuhe desinfektion bettschutz einlagen hautpflege apotheke inkontinenz 42 euro', label: 'Pflegeprodukte & Pflegebox', short: 'Pflegeprodukte', hint: 'Apotheken und Sanitätshäuser', match: [['sanitaetshaus', 'pflegehilfsmittel'], ['sanitaetshaus', 'stoma'], ['apotheke', '*']], seite: 'pflegeprodukte', ohneKarte: true },
  { key: 'alltag', words: 'alltagshilfen alltagshelfer alltagshilfe strumpfanzieher anziehhilfe knöpfhilfe schuhlöffel greifzange greifhilfe toilettensitzerhöhung badewannenlifter duschhocker duschstuhl haltegriff badewannenbrett besteck griffverdickung trinkbecher tellerranderhöhung aufstehhilfe senioren', label: 'Alltagshilfen für Senioren', short: 'Alltagshelfer', hint: 'Anziehen, Bad, Essen, Greifen', match: [['sanitaetshaus', '*']], seite: 'alltagshelfer', ohneKarte: true },
  { key: 'sanitaetshaus', words: 'sanitätshaus sanitaetshaus hilfsmittel orthopädie', label: 'Sanitätshaus allgemein', short: 'Sanitätshaus', match: [['sanitaetshaus', '*']] },
];
export const bedarfMask = (entry) => BEDARF.reduce((m, b, i) => (b.match.some(([c, f]) => entry.cat === c && (f === '*' || entry.features.includes(f))) ? m | (1 << i) : m), 0);
